import type { Metadata } from 'next'
import Link from 'next/link'
import { OperatingConstraintMap } from '../../components/consulting-artifacts'
import { SectionLabel } from '../../components/editorial/SectionLabel'
import { SERVICES } from '../../content/services'

export const metadata: Metadata = { title: 'Business Consultancy in Bangladesh', description: 'Productised AI implementation and management operations strategy for small and medium businesses in Bangladesh.', alternates: { canonical: '/business-consultancy-bangladesh' } }

export default function BangladeshConsultancyPage() {
  return <main><header className="local-hero" data-nav-theme="light"><SectionLabel>Bangladesh</SectionLabel><h1 className="display display--xl">Business consultancy for operators who need <span className="authority">something usable.</span></h1><p className="lede">Zaser &amp; Co is a Dhaka-based strategic and management consultancy serving small and medium businesses through two fixed-scope engagements.</p></header><section className="local-context section section--navy" data-nav-theme="dark"><div><SectionLabel light>Local operating context</SectionLabel><h2 className="display display--lg">Clarity before <span className="authority">complexity compounds.</span></h2><p className="lede">Growing businesses coordinate pricing, cost, process, people, technology, and customer expectations at the same time. The right engagement makes those dependencies visible before prescribing change.</p></div><OperatingConstraintMap scope="bangladesh" tone="navy" /></section><section className="local-services section section--white" data-nav-theme="light"><SectionLabel>Two engagements</SectionLabel>{SERVICES.map((service) => <Link key={service.slug} href={`/services/${service.slug}`}><span>{service.number}</span><h2 className="display display--md">{service.title}</h2><p>{service.description}</p><strong>Explore ↗</strong></Link>)}</section><section className="route-cta section section--paper" data-nav-theme="light"><SectionLabel>Free business audit</SectionLabel><h2 className="display display--lg">Start with a <span className="authority">clearer question.</span></h2><p className="lede">Tell us where the operation feels stuck. We’ll identify the most useful first line of inquiry.</p><Link className="button button--rust" href="/free-business-audit"><span>Request your audit</span><span aria-hidden="true">↗</span></Link></section></main>
}
