import type { Metadata } from 'next'
import Link from 'next/link'
import { OperatingConstraintMap } from '../../components/consulting-artifacts'
import { SectionLabel } from '../../components/editorial/SectionLabel'
import { SERVICES } from '../../content/services'

export const metadata: Metadata = { title: 'Business Consultant in Dhaka', description: 'Dhaka-based business consultancy for operational performance and practical AI implementation.', alternates: { canonical: '/business-consultant-dhaka' } }

export default function DhakaConsultantPage() {
  return <main><header className="local-hero" data-nav-theme="light"><SectionLabel>Dhaka</SectionLabel><h1 className="display display--xl">A business consultant should leave more than a <span className="authority">recommendation.</span></h1><p className="lede">Zaser &amp; Co works with Dhaka operators who need clearer cost, process, and technology decisions, plus a tangible output their team can use.</p></header><section className="local-context section section--navy" data-nav-theme="dark"><div><SectionLabel light>How the work begins</SectionLabel><h2 className="display display--lg">Diagnose the operating <span className="authority">constraint.</span></h2><p className="lede">We start with the operation as it exists: the numbers available, the work people perform, the tools already in use, and the decisions that remain difficult.</p></div><OperatingConstraintMap scope="dhaka" tone="navy" /></section><section className="local-services section section--white" data-nav-theme="light"><SectionLabel>Two engagements</SectionLabel>{SERVICES.map((service) => <Link key={service.slug} href={`/services/${service.slug}`}><span>{service.number}</span><h2 className="display display--md">{service.title}</h2><p>{service.description}</p><strong>Explore ↗</strong></Link>)}</section><section className="route-cta section section--paper" data-nav-theme="light"><SectionLabel>Start locally</SectionLabel><h2 className="display display--lg">Bring the operating <span className="authority">tension.</span></h2><p className="lede">A focused first conversation is enough to determine whether a Zaser engagement fits.</p><Link className="button button--rust" href="/contact"><span>Contact Zaser &amp; Co</span><span aria-hidden="true">↗</span></Link></section></main>
}
